import React from "react";
import { NFTList, Pagination } from "../../components";
import OverviewIntroduction from "./OverviewIntroduction";
const HomePage = () => {
  const arrayNFT = [
    {
      id: 1,
      name: "Love Cake",
      price: 9.99,
      owner: null,
      published_at: "2022-08-07T12:44:49.747Z",
      created_by: {
        id: 1,
        firstname: "Thanh Tien",
        lastname: "Nguyen",
        username: null,
        email: "tiennt0212@gmail.com",
        isActive: true,
        blocked: null,
        preferedLanguage: null,
      },
      updated_by: {
        id: 1,
        firstname: "Thanh Tien",
        lastname: "Nguyen",
        username: null,
        email: "tiennt0212@gmail.com",
        isActive: true,
        blocked: null,
        preferedLanguage: null,
      },
      created_at: "2022-08-07T12:44:41.399Z",
      updated_at: "2022-08-07T12:44:49.766Z",
      image: {
        id: 1,
        name: "love_cake.jpg",
        alternativeText: "",
        caption: "",
        width: 564,
        height: 723,
        formats: {
          thumbnail: {
            name: "thumbnail_love_cake.jpg",
            hash: "thumbnail_love_cake_16eb87c6c8",
            ext: ".jpg",
            mime: "image/jpeg",
            width: 122,
            height: 156,
            size: 3.19,
            path: null,
            url: "/uploads/thumbnail_love_cake_16eb87c6c8.jpg",
          },
          small: {
            name: "small_love_cake.jpg",
            hash: "small_love_cake_16eb87c6c8",
            ext: ".jpg",
            mime: "image/jpeg",
            width: 390,
            height: 500,
            size: 17.43,
            path: null,
            url: "/uploads/small_love_cake_16eb87c6c8.jpg",
          },
        },
        hash: "love_cake_16eb87c6c8",
        ext: ".jpg",
        mime: "image/jpeg",
        size: 26.26,
        url: "/uploads/love_cake_16eb87c6c8.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        created_by: 1,
        updated_by: 1,
        created_at: "2022-08-07T12:44:22.355Z",
        updated_at: "2022-08-07T12:44:22.364Z",
      },
    },
    {
      id: 1,
      name: "Love Cake",
      price: 9.99,
      owner: null,
      published_at: "2022-08-07T12:44:49.747Z",
      created_by: {
        id: 1,
        firstname: "Thanh Tien",
        lastname: "Nguyen",
        username: null,
        email: "tiennt0212@gmail.com",
        isActive: true,
        blocked: null,
        preferedLanguage: null,
      },
      updated_by: {
        id: 1,
        firstname: "Thanh Tien",
        lastname: "Nguyen",
        username: null,
        email: "tiennt0212@gmail.com",
        isActive: true,
        blocked: null,
        preferedLanguage: null,
      },
      created_at: "2022-08-07T12:44:41.399Z",
      updated_at: "2022-08-07T12:44:49.766Z",
      image: {
        id: 1,
        name: "love_cake.jpg",
        alternativeText: "",
        caption: "",
        width: 564,
        height: 723,
        formats: {
          thumbnail: {
            name: "thumbnail_love_cake.jpg",
            hash: "thumbnail_love_cake_16eb87c6c8",
            ext: ".jpg",
            mime: "image/jpeg",
            width: 122,
            height: 156,
            size: 3.19,
            path: null,
            url: "/uploads/thumbnail_love_cake_16eb87c6c8.jpg",
          },
          small: {
            name: "small_love_cake.jpg",
            hash: "small_love_cake_16eb87c6c8",
            ext: ".jpg",
            mime: "image/jpeg",
            width: 390,
            height: 500,
            size: 17.43,
            path: null,
            url: "/uploads/small_love_cake_16eb87c6c8.jpg",
          },
        },
        hash: "love_cake_16eb87c6c8",
        ext: ".jpg",
        mime: "image/jpeg",
        size: 26.26,
        url: "/uploads/love_cake_16eb87c6c8.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        created_by: 1,
        updated_by: 1,
        created_at: "2022-08-07T12:44:22.355Z",
        updated_at: "2022-08-07T12:44:22.364Z",
      },
    },
  ];
  return (
    <React.Fragment>
      <OverviewIntroduction />
      <NFTList nfts={arrayNFT} />
      <Pagination totalCount={42} pageSize={6} currentPage={5} />
    </React.Fragment>
  );
};

export default HomePage;
